# Generated by Django 4.0.3 on 2022-04-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_no',
            new_name='phone_number',
        ),
    ]
